name: Snakes CI
env:
  ECRURI: 054017840000.dkr.ecr.us-east-1.amazonaws.com
  AppRepoName: snakes
  Tag: ${{ github.sha }}
  StartVersionFrom: 0.0.1

on:
  push:
    branches: github-ci

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Versioning
      run: |
        version=$(git describe --tags `git rev-list --tags --max-count=1` || echo $StartVersionFrom)
        A=$(echo $version | cut -d '.' -f 1)
        B=$(echo $version | cut -d '.' -f 2)
        C=$(echo $version | cut -d '.' -f 3)
        echo " *** ORIGIN VERSION A=$A, B=$B, C=$C *** "
        C=$(echo $version | cut -d '.' -f 3)+1
        echo $C
        echo "$A.$B.$C"
        Tag = "$A.$B.$C"
        echo $Tag

    - name: Build the App
      run: cd eb-tomcat-snakes && ./build.sh

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $ECRURI/$AppRepoName:$Tag

    - name: Test
      run: |
        docker run -d -p 8090:8080 --name test $ECRURI/$AppRepoName:$Tag
        sleep 10
        curl -sS http://localhost:8090 | grep "Does it have snakes?"
        docker rm -f test

    - name: check
      run: docker images
